# Generated by Django 4.2.7 on 2025-11-29 20:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('risk_type', models.CharField(choices=[('auto_renewal', 'Auto-Renewal Risk'), ('unlimited_liability', 'Unlimited Liability'), ('broad_indemnity', 'Broad Indemnity'), ('termination_imbalance', 'Termination Imbalance'), ('unfavorable_payment', 'Unfavorable Payment Terms'), ('weak_confidentiality', 'Weak Confidentiality'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('evidence_text', models.TextField()),
                ('char_start', models.IntegerField(blank=True, null=True)),
                ('char_end', models.IntegerField(blank=True, null=True)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('detection_method', models.CharField(default='hybrid', max_length=50)),
                ('rule_matched', models.CharField(blank=True, max_length=200, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'audit_findings',
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractExtraction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parties', models.JSONField(blank=True, default=list)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('term', models.CharField(blank=True, max_length=500, null=True)),
                ('governing_law', models.CharField(blank=True, max_length=500, null=True)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('termination', models.TextField(blank=True, null=True)),
                ('auto_renewal', models.JSONField(blank=True, default=dict)),
                ('confidentiality', models.TextField(blank=True, null=True)),
                ('indemnity', models.TextField(blank=True, null=True)),
                ('liability_cap', models.JSONField(blank=True, default=dict)),
                ('signatories', models.JSONField(blank=True, default=list)),
                ('raw_extraction', models.JSONField(blank=True, default=dict)),
                ('model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('extraction_method', models.CharField(default='llm', max_length=50)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contract_extractions',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500)),
                ('file_path', models.FileField(max_length=500, upload_to='contracts/')),
                ('file_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('file_size', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('total_characters', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('page_number', models.IntegerField()),
                ('text_content', models.TextField()),
                ('char_count', models.IntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='api.document')),
            ],
            options={
                'db_table': 'document_pages',
                'ordering': ['document', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('text_content', models.TextField()),
                ('char_start', models.IntegerField()),
                ('char_end', models.IntegerField()),
                ('vector_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='api.document')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='api.documentpage')),
            ],
            options={
                'db_table': 'document_chunks',
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_hash'], name='documents_file_ha_3bbf78_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_status_f31a08_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-uploaded_at'], name='documents_uploade_b9da9c_idx'),
        ),
        migrations.AddField(
            model_name='contractextraction',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='api.document'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_findings', to='api.document'),
        ),
        migrations.AddIndex(
            model_name='documentpage',
            index=models.Index(fields=['document', 'page_number'], name='document_pa_documen_6d98e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentpage',
            unique_together={('document', 'page_number')},
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='document_ch_documen_15f3c0_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['vector_id'], name='document_ch_vector__133003_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together={('document', 'chunk_index')},
        ),
        migrations.AddIndex(
            model_name='contractextraction',
            index=models.Index(fields=['document'], name='contract_ex_documen_bf69c5_idx'),
        ),
        migrations.AddIndex(
            model_name='contractextraction',
            index=models.Index(fields=['-created_at'], name='contract_ex_created_141f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['document'], name='audit_findi_documen_6c40de_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['severity'], name='audit_findi_severit_afb6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['risk_type'], name='audit_findi_risk_ty_58e341_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['-created_at'], name='audit_findi_created_39ddff_idx'),
        ),
    ]
